version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=kanban
      - POSTGRES_PASSWORD=1234
    ports: 
      - '5434:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      

  app:
    build: .
    command: npm run start-dev
    ports: 
      - '5000:5000'
    volumes: 
      - .:/usr/app
    depends_on:
      - db  


